name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install html-minifier terser clean-css-cli -g

      - name: Minify inline HTML, JS, and CSS
        run: |
          # Minify HTML including inline CSS and JS
          html-minifier \
            --collapse-whitespace \
            --remove-comments \
            --minify-css true \
            --minify-js '{ "compress": true, "mangle": false }' \
            -o dist/index.html index.html

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          enable_jekyll: false
          
